"""new fields in posts  model

Revision ID: 3c15d25da59a
Revises: dcf01d8990c1
Create Date: 2020-06-08 20:57:04.529110

"""

# revision identifiers, used by Alembic.
revision = '3c15d25da59a'
down_revision = 'dcf01d8990c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
